version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/saree-backend-temp
hooks:
  ApplicationStop:
    - location: sudo chmod +x scripts/stop_server.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application_start.sh 
      timeout: 300